"""empty message

Revision ID: 01368a3a906b
Revises: 5e10a128f4c9
Create Date: 2020-09-14 12:46:33.026557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01368a3a906b'
down_revision = '5e10a128f4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('member')
    op.add_column('user_profile', sa.Column('member_number', sa.TEXT(), nullable=True))
    op.drop_constraint('user_profile_member_id_fkey', 'user_profile', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile', 'member_type', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.create_foreign_key('user_profile_member_id_fkey', 'user_profile', 'member', ['member_id'], ['id'])
    op.drop_column('user_profile', 'member_number')
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='member_pkey')
    )
    op.drop_table('member_type')
    # ### end Alembic commands ###
