"""empty message

Revision ID: 05f36e6903c6
Revises: 3173cbb83557
Create Date: 2020-09-26 06:42:08.066673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f36e6903c6'
down_revision = '3173cbb83557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('first_name_roman', sa.TEXT(), nullable=True))
    op.add_column('user_profile', sa.Column('last_name_roman', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'last_name_roman')
    op.drop_column('user_profile', 'first_name_roman')
    # ### end Alembic commands ###
