"""empty message

Revision ID: 0e7101b37678
Revises: 4fc4aa657f3a
Create Date: 2020-09-26 19:31:58.170025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7101b37678'
down_revision = '4fc4aa657f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_id', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('member_type_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('member_validate', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'member_type', ['member_type_id'], ['id'])
    op.drop_constraint('user_profile_member_id_fkey', 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'member_number')
    op.drop_column('user_profile', 'member_validate')
    op.drop_column('user_profile', 'member_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('member_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('member_validate', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_profile', sa.Column('member_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_profile_member_id_fkey', 'user_profile', 'member_type', ['member_type_id'], ['id'])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'member_validate')
    op.drop_column('user', 'member_type_id')
    op.drop_column('user', 'member_id')
    # ### end Alembic commands ###
