"""empty message

Revision ID: 18e91175ad06
Revises: e30d538cc2c1
Create Date: 2020-09-16 20:55:33.429469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e91175ad06'
down_revision = 'e30d538cc2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('papers', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'papers')
    # ### end Alembic commands ###
