"""empty message

Revision ID: 288077754681
Revises: 6062681e8b0f
Create Date: 2020-09-24 15:01:09.557662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288077754681'
down_revision = '6062681e8b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attend_user', sa.Column('cancel', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_attend_user', 'cancel')
    # ### end Alembic commands ###
