"""empty message

Revision ID: 29d742a12c49
Revises: 05f36e6903c6
Create Date: 2020-09-26 06:43:01.211800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d742a12c49'
down_revision = '05f36e6903c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'first_name_roman',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_profile', 'last_name_roman',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'last_name_roman',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_profile', 'first_name_roman',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
