"""empty message

Revision ID: 2bf33ffcfaaf
Revises: e3c4889990ce
Create Date: 2020-09-11 03:55:37.077031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf33ffcfaaf'
down_revision = 'e3c4889990ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user_profile', 'address_type', ['address_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_table('address_type')
    # ### end Alembic commands ###
