"""empty message

Revision ID: 303c8e7bca3a
Revises: 38cdaf0eaf87
Create Date: 2020-09-07 20:03:13.649138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303c8e7bca3a'
down_revision = '38cdaf0eaf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('organization', sa.TEXT(), nullable=False),
    sa.Column('department', sa.TEXT(), nullable=False),
    sa.Column('test', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
