"""empty message

Revision ID: 3173cbb83557
Revises: 352eaaf56d49
Create Date: 2020-09-26 06:41:05.518934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3173cbb83557'
down_revision = '352eaaf56d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('first_name_roman', sa.TEXT(), nullable=False))
    op.add_column('user_profile', sa.Column('last_name_roman', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'last_name_roman')
    op.drop_column('user_profile', 'first_name_roman')
    # ### end Alembic commands ###
