"""empty message

Revision ID: 352eaaf56d49
Revises: 2cba5a38b554
Create Date: 2020-09-25 20:56:15.420705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352eaaf56d49'
down_revision = '2cba5a38b554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'member_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'member_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
