"""empty message

Revision ID: 38cdaf0eaf87
Revises: eede91e97e07
Create Date: 2020-09-07 19:44:39.467716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cdaf0eaf87'
down_revision = 'eede91e97e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('state', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    # ### end Alembic commands ###
