"""empty message

Revision ID: 43d625d1532e
Revises: 68fff9b0a5f3
Create Date: 2020-09-25 15:06:49.189527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d625d1532e'
down_revision = '68fff9b0a5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'member_validate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'member_validate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
