"""empty message

Revision ID: 5221fad5bdc3
Revises: 01368a3a906b
Create Date: 2020-09-14 12:49:10.601405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5221fad5bdc3'
down_revision = '01368a3a906b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('member_number', sa.TEXT(), nullable=True),
    sa.Column('first_name', sa.TEXT(), nullable=False),
    sa.Column('last_name', sa.TEXT(), nullable=False),
    sa.Column('first_name_kana', sa.TEXT(), nullable=False),
    sa.Column('last_name_kana', sa.TEXT(), nullable=False),
    sa.Column('organization', sa.TEXT(), nullable=False),
    sa.Column('department', sa.TEXT(), nullable=True),
    sa.Column('address_type', sa.Integer(), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('prefecture', sa.TEXT(), nullable=False),
    sa.Column('municipalities', sa.TEXT(), nullable=False),
    sa.Column('address1', sa.TEXT(), nullable=False),
    sa.Column('address2', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['address_type'], ['address_type.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member_type.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('member_type')
    # ### end Alembic commands ###
