"""empty message

Revision ID: 540bf55ea82e
Revises: 5221fad5bdc3
Create Date: 2020-09-15 12:01:07.869493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540bf55ea82e'
down_revision = '5221fad5bdc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('english_name', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('date', sa.ARRAY(sa.DateTime()), nullable=True),
    sa.Column('attend_period', sa.DateTime(), nullable=True),
    sa.Column('presenting_papers_period', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('attend_date', sa.ARRAY(sa.DateTime()), nullable=True),
    sa.Column('papers', sa.Boolean(), nullable=False),
    sa.Column('social', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uix_user_id_event_id')
    )
    op.add_column('user_profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_profile_account_id_fkey', 'user_profile', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile', 'user', ['user_id'], ['id'])
    op.drop_column('user_profile', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.create_foreign_key('user_profile_account_id_fkey', 'user_profile', 'user', ['account_id'], ['id'])
    op.drop_column('user_profile', 'user_id')
    op.drop_table('event_user')
    op.drop_table('event')
    # ### end Alembic commands ###
