"""empty message

Revision ID: 5d32ae4269d9
Revises: c69a27dd50b3
Create Date: 2020-09-16 18:20:23.085788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d32ae4269d9'
down_revision = 'c69a27dd50b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_presentation_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('papers', sa.Boolean(), nullable=True),
    sa.Column('attend_social_gathering', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='event_presentation_uix_user_id_event_id')
    )
    op.add_column('event_attend_user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('event_attend_user', sa.Column('expect_papers', sa.Boolean(), nullable=True))
    op.add_column('event_attend_user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('event_attend_uix_user_id_event_id', 'event_attend_user', ['user_id', 'event_id'])
    op.drop_constraint('uix_user_id_event_id', 'event_attend_user', type_='unique')
    op.drop_column('event_attend_user', 'papers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_attend_user', sa.Column('papers', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uix_user_id_event_id', 'event_attend_user', ['user_id', 'event_id'])
    op.drop_constraint('event_attend_uix_user_id_event_id', 'event_attend_user', type_='unique')
    op.drop_column('event_attend_user', 'updated_at')
    op.drop_column('event_attend_user', 'expect_papers')
    op.drop_column('event_attend_user', 'created_at')
    op.drop_table('event_presentation_user')
    # ### end Alembic commands ###
