"""empty message

Revision ID: 6062681e8b0f
Revises: e72597efc0f2
Create Date: 2020-09-17 00:44:39.163475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6062681e8b0f'
down_revision = 'e72597efc0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'address_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'address_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
