"""empty message

Revision ID: 68fff9b0a5f3
Revises: accbb4c28c91
Create Date: 2020-09-25 15:00:54.858797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68fff9b0a5f3'
down_revision = 'accbb4c28c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('member_type_id', sa.Integer(), nullable=False),
    sa.Column('participation', sa.Integer(), nullable=False),
    sa.Column('papers', sa.Integer(), nullable=False),
    sa.Column('social_gathering', sa.Integer(), nullable=False),
    sa.Column('corporate_exhibition', sa.Integer(), nullable=False),
    sa.Column('web_advertising_banner', sa.Integer(), nullable=False),
    sa.Column('web_advertising_small', sa.Integer(), nullable=False),
    sa.Column('web_advertising_medium', sa.Integer(), nullable=False),
    sa.Column('web_advertising_large', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['member_type_id'], ['member_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profile', sa.Column('member_validate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'member_validate')
    op.drop_table('event_fee')
    # ### end Alembic commands ###
