"""empty message

Revision ID: 698e18ade029
Revises: a821f85f0314
Create Date: 2020-09-16 12:28:40.217061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698e18ade029'
down_revision = 'a821f85f0314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('event_form_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('social_gathering', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'event', 'event_form', ['event_form_id'], ['id'])
    op.add_column('event_user', sa.Column('attend_social_gathering', sa.Boolean(), nullable=False))
    op.drop_column('event_user', 'social')
    op.add_column('society', sa.Column('abbreviation', sa.TEXT(), nullable=True))
    op.alter_column('society', 'english_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('society', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('society', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('society', 'english_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('society', 'abbreviation')
    op.add_column('event_user', sa.Column('social', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('event_user', 'attend_social_gathering')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'social_gathering')
    op.drop_column('event', 'event_form_id')
    op.drop_table('event_form')
    # ### end Alembic commands ###
