"""empty message

Revision ID: 784ac2987b64
Revises: caa6582432fa
Create Date: 2020-09-07 23:39:47.875378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784ac2987b64'
down_revision = 'caa6582432fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.TEXT(), nullable=True))
    op.add_column('user', sa.Column('token_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_period')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
