"""empty message

Revision ID: 99caf18b0771
Revises: 0e7101b37678
Create Date: 2020-09-26 19:33:31.351644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99caf18b0771'
down_revision = '0e7101b37678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'member_validate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'member_validate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
