"""empty message

Revision ID: 9c7b0ca72d4e
Revises: 288077754681
Create Date: 2020-09-25 14:40:27.390074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7b0ca72d4e'
down_revision = '288077754681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_fee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('participation', sa.Integer(), nullable=False),
    sa.Column('papers', sa.Integer(), nullable=False),
    sa.Column('social_gathering', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_fee')
    # ### end Alembic commands ###
