"""empty message

Revision ID: 9d2b8d5de6d9
Revises: 18e91175ad06
Create Date: 2020-09-16 21:05:55.776390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2b8d5de6d9'
down_revision = '18e91175ad06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('has_papers', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('has_social_gathering', sa.Boolean(), nullable=True))
    op.drop_column('event', 'papers')
    op.drop_column('event', 'social_gathering')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('social_gathering', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('papers', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('event', 'has_social_gathering')
    op.drop_column('event', 'has_papers')
    # ### end Alembic commands ###
