"""empty message

Revision ID: a821f85f0314
Revises: 540bf55ea82e
Create Date: 2020-09-15 12:59:56.034484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a821f85f0314'
down_revision = '540bf55ea82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'english_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('event', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('event', 'english_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
