"""empty message

Revision ID: accbb4c28c91
Revises: 9c7b0ca72d4e
Create Date: 2020-09-25 14:43:47.578965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accbb4c28c91'
down_revision = '9c7b0ca72d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_fee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_fee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('papers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('social_gathering', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_fee_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_fee_pkey')
    )
    # ### end Alembic commands ###
