"""empty message

Revision ID: bf20aeec6442
Revises: 9d2b8d5de6d9
Create Date: 2020-09-17 00:17:57.769761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf20aeec6442'
down_revision = '9d2b8d5de6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profile_address_type_fkey', 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'address_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_profile_address_type_fkey', 'user_profile', 'address_type', ['address_type'], ['id'])
    # ### end Alembic commands ###
