"""empty message

Revision ID: c64555e0d4b0
Revises: 9697a16d2d44
Create Date: 2020-09-17 00:39:33.627265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64555e0d4b0'
down_revision = '9697a16d2d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('address_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_profile', 'address_type', ['address_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'address_type')
    # ### end Alembic commands ###
