"""empty message

Revision ID: e30d538cc2c1
Revises: 5d32ae4269d9
Create Date: 2020-09-16 18:22:32.187388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e30d538cc2c1'
down_revision = '5d32ae4269d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_presentation_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_presentation_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('papers', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attend_social_gathering', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_presentation_user_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='event_presentation_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_presentation_user_pkey'),
    sa.UniqueConstraint('user_id', 'event_id', name='event_presentation_uix_user_id_event_id')
    )
    # ### end Alembic commands ###
