"""empty message

Revision ID: e72597efc0f2
Revises: 95824ac7aa24
Create Date: 2020-09-17 00:43:12.521856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72597efc0f2'
down_revision = '95824ac7aa24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('address_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_profile_address_type_fkey', 'user_profile', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile', 'address_type', ['address_type_id'], ['id'])
    op.drop_column('user_profile', 'address_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('address_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.create_foreign_key('user_profile_address_type_fkey', 'user_profile', 'address_type', ['address_type'], ['id'])
    op.drop_column('user_profile', 'address_type_id')
    # ### end Alembic commands ###
